# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/centos8"
    config.vm.hostname = "nodejs.test"
    config.vm.network :private_network, ip: "192.168.55.55"
    config.vm.network "forwarded_port", guest: 80, host: 3000
    config.ssh.insert_key = false  
    config.vm.synced_folder ".", "/vagrant", disabled: true
  
    config.vm.provider :virtualbox do |v|
      v.memory = 256
    end

    # Ansible provisioner.
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "main.yml"
      end
    
  end
  