---
- name: Install apache.
  hosts: all
  become: true

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found: 
        - vars/apache_{{ ansible_os_family }}.yml
        - vars/apache_default.yml

  tasks:
    - name: Ensure apache is installed.
      package: 
        name: "{{ apache_package }}"
        state: present

    - name: Copy test config file.
      copy:
        src: files/test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify: restart apache

    - name: Ensure Apache is started and at boot.
      service: 
        name: "{{ apache_service }}"
        state: started
        enabled: true
